### PR TITLE
Add comparison tests with official inky

### PR DESCRIPTION
**Pull request by marcandre**
This uses `inky-cli` to compare the results of the Ruby gem to the node version.

It checks to insure that `inky-cli` is installed correctly and of the right version.

I've only provided a very basic case and it gives me an error:
```
  1) Inky-rb compared to inky-cli for grid components provides the same results for container
     Failure/Error: expect(output_str).to eql(expected_str)

       expected: "<?xmlversion=\"1.0\"?><tablealign=\"center\"class=\"container\"><tbody><tr><td>foo</td></tr></tbody></table>"
            got: "<?xmlversion=\"1.0\"?><tableclass=\"container\"><tbody><tr><td>foo</td></tr></tbody></table>"
```

@kball can you confirm there's a discrepancy here that should be fixed? Also, please :+1: this PR, I'll merge it create more test cases...

### CODE REVIEW

**Comment by kball** [comment]
👍 

One thing to know is there is at least one attribute that inky-node adds to some tags that is due to an implementation problem in the node version (data-parsed on center tags), that I left off for inky-rb, because it is purely working around an implementation issue rather than actually relevant for the output.

**Comment by kball** [comment]
The align on container appears to have been updated in inky-node more recently than the last work on inky-rb, and its definitely there in inky-node, so that bug appears to be real.

**Comment by marcandre** [comment]
So I've added all the examples I could think of, based on the inky docs.

We have 10 failures, 1 of which is inky-node converting some XHTML to HTML (e.g. `<br/>` to `<br>`). All the others are `inky-rb`'s. None are fixed yet; they are marked as 'pending'.

I noticed the official docs don't mention `size-sm` and `size-lg` for `<spacer>`

**Comment by marcandre** [comment]
Found another bug, in both `inky-rb` and `inky-node` about the HTML/XHTML mixup with boolean attributes, but `inky-rb` is worse. Ok, time for bed

**Comment by marcandre** [comment]
Ok, this PR is pretty much complete. It fixes all 13 or so cases where `inky-rb` wasn't in line with `inky-node`, as well as ~4 opened issues. Only one discrepancy remains where it's really `inky-node` that is wrong.

I'd merge this and release as `1.3.7.0`... Ok with you @kball?

**Comment by kball** [comment]
Freaking awesome man.  👍

**Comment by marcandre** [comment]
Actually, re-read about boolean attributes, what inky-node is doing is fine (`b`, `b=""` or `b="b"` are all equivalent for that purpose), so with after this PR, `inky-rb` matches `inky-node` perfectly as far as I can tell. Removing the last case then and merging :smile:

**Comment by marcandre** [comment]
Merged and released :smile:

**Pull request closed without merging**
